### ISSUE TITLE
CORE JAVA ROADMAP

### ISSUE THREAD

**Issue by aditya0608** [aditya0608/JavaInterviewQuestions#1]
```
Effective Use of IDE/Code Editor
```
- [ ] [IntelliJ](https://www.youtube.com/watch?v=yefmcX57Eyg&t=2s) 
- [ ] [Eclipse](https://www.youtube.com/watch?v=0smG768uUis)

```
Version Control Tutorial
```
- [ ] [Github](https://www.youtube.com/watch?v=HCeBd5GKNO8)

```
Java Basics
```
- [ ] [Data Types](https://www.youtube.com/watch?v=MuALK4KcNMc)
- [ ] [Variables](https://www.youtube.com/watch?v=h1Sq8p2GL2g)
- [ ] [Looping Constructs](https://www.youtube.com/watch?v=dw-4mDaxPu8&list=PLBlnK6fEyqRg6C59rGqy0Yt1jJAdhWMUz&index=2)
